data("Groceries")
View(Groceries)
size(Groceries)
length(Groceries)
inspect(Groceries)
inspect(Groceries[1:5])
itemFrequencyPlot(Groceries,topN=10,type="absolute")
itemsets<-apriori(Groceries,parameter = list(minlen=1,maxlen=1,support=0.02,target="frequent itemsets"))
inspect(head(sort(itemsets,by="support"),10))
itemsets<-apriori(Groceries,parameter = list(minlen=1,maxlen=2,support=0.02,target="frequent itemsets"))
inspect(head(sort(itemsets,by="support"),20))
itemsets<-apriori(Groceries,parameter = list(minlen=3,maxlen=3,support=0.02,target="frequent itemsets"))
inspect(head(sort(itemsets,by="support"),10))
rules<-apriori(Groceries,parameter = list(support=0.001,confidence=0.6,target="rules"))
inspect(head(sort(rules,by="lift"),10))
strong_rules<-sort(rules,by="confidence",decreasing = T)
inspect(strong_rules)
